---
title: "Discussion"
output: 
  html_notebook
  # bookdown::html_document2:
    # number_sections: FALSE
bibliography: ../../library.bib
link-citations: TRUE
---


<!-- # outline{-} -->
<!-- 1.  assess hypotheses -->
<!-- 2.  infer causes of patterns - plantation structure, old legacy trees, or species traits? -->
<!-- 3.  compare inferences to other studies -->
<!-- 4.  recommend future conservation approaches, ecological studies -->


<!-- # draft{-} -->


This study found significant edge effects on secondary forest stand wood and stem density, tree diversity and community composition, and some functional traits, yet not on overall aboveground biomass.
<!-- These results were shown in Figs \@ref(fig:biomass), \@ref(fig:taxa), and \@ref(fig:traits)... -->
It was initially hypothesized that community composition would vary with distance to high-quality intact primary forest edge, favoring more shade-tolerant taxa, due to light availability and dispersal potential.
The evidence presented here supported edge effects on community composition and biomass of taxa that were associated with both early- and late-successional stages, but without detectable roles for light availability or general dispersal mode.
Accordingly, this suggests that edge effects do significantly change humid tropical forest community taxonomic and functional composition, but primarily due to factors other than light competition or dispersal limitation *[@krishnadas20]*, and also suggests that aboveground biomass and even low taxonomic richness are resilient after a decade of regeneration.

<!-- ## Biomass -->

Aboveground biomass storage is a key global ecosystem function and service, but edge effects tend to release about one-third of carbon lost from tropical deforestation *[@brinck17]*, with more expected in the future *[@mitchard18]*.
<!-- responds variably to secondary succession and edge effects ...   -->
Management has been found to explain most of biomass variation among tropical forest fragments, and wood density ~10% biomass variation *[@pyles22]*.
Additionally, this study contributes that management via edge effects can also mediate ~10% of wood density variation without affecting local biomass, although median stem wood density can describe regional spatial biomass patterns *[@baker04]*.
In this study, wood density and richness values may have been pulled down by early-successional clonal trees closest to the primary forest, which tend to have lower wood densities, lowering carbon *[@gonzalezj98; @pyles22]*, and increasing nearby stem density.
Lower wood density can also reflect more dynamic forest stands *[@malhi06]* with higher tree turnover, a consequence of forest fragmentation *[@nascimento04]* together with other global change drivers *[@laurance14]*, and may also reflect possible differences in soil fertility *[@malhi04]*, all of which represent possible future research directions, beyond strictly neutral dynamics *[@terborgh95]*.
Furthermore, light availability at the plot level did not affect biomass storage, but instead, individual light gaps may be more important for biomass dynamics *[@chazdon84]*.
    <!-- - although canopy light may still affect biomass generally in this case, without edge effects (check direct light-biomass correlation graph? -- no sig correlation) -->

<!-- ## Composition -->

Edge effects have been shown in other studies not only to lower forest biomass, but also to change community composition *[@anderson22]*, and in addition this study contributes that the decline in diversity can be rapid and non-linear across edge gradients, along with supporting the likelihood of changes to community composition lasting decades.
This rapid loss of diversity across the edge gradient may be in part due to existing higher yet constant levels of shade limiting shade-intolerant seedling recruitment and/or performance, together with insufficient time for slower-growing shade-tolerant taxa to accumulate significant amounts of biomass.
Another possible factor may be Janzen-Connell processes *[@wills06; @terborgh20]*, including conspecific negative density-dependence of seedling survival on basal area *[@comita09]*, as well as overall short dispersal kernels, whose effects can be mediated by shade *[@comita14]* and in part by higher fungal pathogen pressure near conspecifics *[@jia20]*.
While both diversity and community composition changed significantly with distance to intact forest in this study, the biomass of most individual taxa, surprisingly, tended to stay the same along the edge gradient.
This lack of significant individual taxon biomass responses along this edge gradient could be due to stochastic population factors affecting their biomass growth, perhaps widening variability.
Regardless of the underlying process, these absent patterns do also help explain the lack of pattern observed with plot biomass overall across the edge gradient.
This explanation points to future studies of taxon-specific responses to edge effects, to help explain overall forest biomass dynamics near habitat edge.
More specifically here, the biomass of the most abundant taxon *Vochysia* was resilient to edge effects in this study, however, that of the taxon *Ficus*, key for frugivores like birds and bats *[@cottee-jones15; @rafidison20]*, was significantly lowered across the secondary forest edge, pointing to potentially different responses of biomass and local food web associated ecosystem services.
Results suggest that this pattern is specific to this locally widespread *Ficus* genus, since the overall biomass of other animal-dispersed taxa as a whole tended to stay the same across the edge gradient studied here.
Interestingly, community composition also appeared to show lower variance across the edge gradient, although testing this observation in a forested area with evenly distributed area among distance strata bands would provide additional support.

<!-- ## Traits -->

Characterizing community composition by functional traits is also increasingly studied *[@kearney21]*, but less so regarding edge effects.
A study in Madagascar found lower phylogenetic diversity closer to degraded forest edge, but no change in aboveground biomass *[@razafindratsima18]*.
This study presents similar results in showing lower taxonomic diversity, although biomass specifically of taxa associated with both early- and late-successional stages also decreased with away from primary forest edge.
This resulting decrease by successional stage could be explained by slightly lower habitat quality inferred near exposed habitat edges near roads, and accordingly relatively higher habitat quality near closed primary forest edge *[@ries04]*.
While lower biomass of succession-agnostic taxa further from primary forest edge appears consistent with the expected forms of group-level dispersal kernels as an explanation, the lack of significant pattern along forest edge when binned by broad dispersal mode that was found here may limit the potential of seed dispersal to explain biomass trends.
Instead, seedling survival may have been more important than dispersal in accumulating basal area and biomass *[@comita09]*.
For taxa primarily dispersed by animals instead of wind, this could be explained by potentially broader local limitations in animal dispersal activity or abundance.
Additionally, the potential for nearby dispersal to facilitate reforestation could be tested in future studies by measuring taxon-specific dispersal kernels.

<!-- ## Conclusion -->

Overall, this study highlights how abandoned wet tropical timber plantation can regenerate in alongside fragmented forests.
Results support related syntheses that tropical forest biomass and taxonomic richness often regrows relatively quickly *[@davies21a]*, 
<!-- **along with traits?,** -->
while taxonomic composition recovers much more slowly, if not diverging altogether *[@norden15]*.
These findings can suggest that more efficient reforestation could more actively target biodiversity conservation over other resilient functions like carbon storage, and that restoration efforts could include focusing activities like native species planting efforts on degraded habitat edges away from primary forest edges, and investing less in areas closer to existing forest edges, where recruitment may already maintain diversity levels.
As forests continue to become fragmented *[@haddad15]*, understanding how to work with natural regeneration patterns around edge effects will likely become increasingly important.


<!-- # draft attic{-} -->

<!-- This study supports previous syntheses suggesting that forest biomass and taxonomic richness regenerate more quickly / are more resilient than diversity and community composition *[@poorter21?, other?]*. -->
<!-- This may be due to priority effects on successional trajectories acting on/at the stem/population level *[]*, variable turnover and reproduction rates among tree taxa *[]*, and/or differential dispersal and establishment success based on local [dispersive] animal community *[]*. ... -->
<!-- - mention more amundant genera patterns w/ *Vochysia* and *Ficus* as a key fruit-bearing taxon *[@tropicalbat/bird]*? -->

<!-- There is increasing interest in functional trait ecology of tropical trees *[@umaña##]*. -->
<!-- This focuses on a coarse functional association with successional stage, ... -->
<!-- but also includes patterns with wood density [underlying biomass estmations]... -->
<!-- - fig3 -- edge effect on succession generalists, but not specialists -->
<!-- The persistence of early-successional tree communities has been found to lower the standing biomass, likely due to lower wood density *[@césar21]*, and could therefore require a switch in focal timber species *[@karsten14]*. -->


<!-- # attic{-} -->


<!-- Under more sustainable forestry that maintains multiple functions, forest stand regeneration is likely more predictable, generally mirroring (i.e. near 1:1 replacement) the targeted tree cutting that is done using information collected about the ecological profiles and ages (when possible) of trees (Duah-Gyamfi et al 2014, Edwards et al 2014). -->

<!-- In contrast, under intensive silviculture that prioritizes the growth of select tree crop species, forest stands can show high wood production (Ferez et al 2015) while also usually showing negative trade-offs with other services, like that with biodiversity given reliance on monoculture planting designs. -->

<!-- In some cases where management decisions are made primarily based on regional economic but not local ecological information, due to limited access to funded scientific reporting (Cook et al 2012), forest stands can perform very poorly all-around. -->

<!-- After this more extreme type of management, it remains uncertain how natural regeneration in secondary forests will proceed, how local ecosystem services will be restored, and how restoration could be managed locally (Laurance et al 2012), e.g. based on surrounding forest proximity. -->
