---
title: "Introduction"
output: html_notebook
bibliography: ../../library.bib
link-citations: TRUE
---



<!-- # Outline -->


<!-- 1.  importance of reforestation/regeneration/regrowth -->
<!-- 2.  patterns of reforestation -->
<!--     1.  general -->
<!--     2.  tropical -->
<!-- 3.  things that affect reforestation -->
<!--     1.  edge effects -->
<!--     2.  plantation structure? -->
<!-- 4.  [for NGO--start biomass census] -->
<!--     1.  Does leaving the plantation structure help reforestation? -->
<!--         1.  shade -->
<!--         2.  edge effects (i.e. buffer) -->
<!--     2.  How does the forest regenerate by distance to primary forest? -->
<!--         1.  how much [effort] do we need to re-seed? / how much can we leave to nature? -->



<!-- # Draft -->


Forest and landscape restoration is a key international conservation and climate change adaptation strategy *[@depinto20]*.
While tropical forests specifically store most land biomass *[@pan13]*, most are now secondary *[@fao20]* and functionally degraded *[@hubau20]*.
This likely amplifies amid increasing climate stressors *[@anderegg22]* and collective management issues, including insufficient policy support *[@chazdon18]* via skewed priorities *[@pyron22]*.
Overall, secondary forests can regenerate relatively quickly compared to old-growth forests, in some ways.
Neotropical secondary forests can grow quickly enough to accumulate biomass >10x faster than old-growth forests *[@finegan96; @poorter16]*, and substantially offset carbon emissions, with estimates ranging from ~10% from Amazonian deforestation *[@smith20]* to a decade of fossil fuel emissions from all of Latin American and the Caribbean *[@chazdon16]*.
They also recover taxonomic richness and biomass quite quickly, as well as tree height, averaging 80% of old-growth forest levels in just 20 years, especially in wetter regions *[@rozendaal19]*.
The recovery of species richness alone is beneficial in that it also tends to correlate with the recovery of some ecosystem services *[@guariguata01; @stanturf14]* like biomass and carbon storage *[@liu18]*.
However, recovery of secondary neotropical forests diverge widely in taxonomic composition *[@norden15]*, potentially taking over a century to recover *[@poorter21]* with added variability *[@atkinson22]*.
Despite being one of the slowest ecosystem properties to recover, restoring recovering community composition is often important for preserving rare taxa *[@carlo16]*, which can be keystone to locally-adapted food webs, including birds *[@maas16]*.
Overall, understanding secondary forest regeneration is key for global biodiversity conservation at the global scale.

Modern secondary forest regeneration is often affected by edge effects, or changes near an ecosystem boundary, especially in heterogeneously-managed landscapes *[@perfecto09; @melo13]*.
About 70% of all forests have been estimated to be within a km of their edge *[@haddad15]*, resulting in tropical forests having been estimated to lose ~22% aboveground carbon along heavily-managed edges >100m, in part due to shortening trees and lighter leaf mass *[@ordway20]*.
Effects of degraded edges have historically favored tree taxa that tend to be pioneering, or be faster-growing, have lower wood densities, and be less shade-tolerant *[@tabarelli08]*.
Accordingly, secondary forest wood density may also tend to decrease near degraded habitat edges.
Additionally, the dominance of pioneering taxa could lead to arrested succession *[@tymen15]*, which further delays the recruitment of shade-tolerant taxa, as well as associated increases in aboveground biomass, in part due to their higher survival with increasing shade, and tendency toward relatively higher wood densities.
However, arrested succession could be prevented, and even typical succession accelerated, if intact forests that were adjacent to regenerating plantations functioned as contributing reservoirs of seeds from later-successional tree taxa.
In this case, having a habitat edge near a relatively rich intact forest, rather than near a relatively degraded open area, would instead be an asset to regenerating plantation forest patches, rather than a detriment.
Overall, edge effects ultimately have the potential to shape community composition, in part based on the local dispersal kernel patterns of existing taxa *[@wandrag17]*, which while complicated *[@muller-landau09]*, can also correlate with simpler plant traits like height and seed mass *[@thomson11; @tamme14]*.

Additionally, properties of the tropical forest carbon stores and tree community depend heavily on land-use history and previous management *[@omeja12; @pyles22]*.
Overall, legacy effects from management like intensive timber planting could potentially delay or result in non-linear changes between successional stages *[@albrich20; @gough21]*, which would make future management more uncertain, unlike more sustainable thinning practices and agroforestry *[@lefland18]*.
In some cases, the leftover timber stands could provide additional shade, which would not be available in a clear-cut harvested timber plantation, and this could help more shade-tolerant taxa establish and recruit better.
Overall, edge effects near degraded habitat edges are often studied as negative, but conceptual influences from meta-population *[@levins79]* and meta-community *[@leibold04; @warren15]* theories do highlight dispersal as a key process for offsetting extinction debt and thus maintaining biodiversity, thereby potentially making particular edge effects, specifically from adjacent intact forests, actually beneficial for regeneration plantation forest parcels.
Taken together, these ideas suggest that edge effects specifically from adjacent intact primary forests, potentially via shade-tolerant dispersal and performance, may indeed facilitate plantation forest regeneration.
Such a beneficial edge effect may ultimately help explain relatively high biodiversity, compared to adjacent stands, found in agroforests *[@oliveira-neto17]*, forests affected by logging *[@clark12; @edwards14]*, and timber plantations *[@pryde15]*.

<!-- role of N-fixing trees... *[@lai18]* -->
<!-- A subset of secondary forests include naturally regenerating timber plantations, which may show unique recovery patterns. -->
<!-- .. -->
<!-- More specifically, regenerating timer plantations may also experience edge effects, but they tend to be ...  -->
<!-- - from *[@anderson22; others]* -->
<!-- - examples of *B. quinata* plantation papers specifically -->

Influenced by restoration ecology for forest management, this study reports tree regeneration patterns of an abandoned wet neotropical timber plantation, focused on highlighting edge effects from an adjacent primary forest on overall stand properties, tree community composition, and limited functional trait recovery.
<!-- **- what is new in this study?** -->
We hypothesized that remaining timber trees would mediate forest regrowth by maintaining shade, which would suppress less shade-tolerant pioneer tree taxa, and in turn facilitate more shade-tolerant tree taxa, ultimately allowing for more tree diversity within the regenerating plantation forest in parts that were closer to the richer edge of the intact unmanaged forest.
    <!-- - supported by inference?! -->
Accordingly, we predicted more specifically that further from the primary forest edge, canopy light availability would increase, while stand biomass and diversity would decrease.

<!-- - conceptual hypothesis diagram? -->



<!-- # attic -->



<!-- Forest regeneration has the potential to store *## C* and preserve *## diversity* globally in the coming decades (UN, Bonn challenge). -->

<!-- At local scales, regeneration is strongly affected by landscape [ecological] heterogeneity as well as management history. -->

<!-- However, patterns of forest regeneration remain unclear, especially at more local scales (< ~50 ha). -->

<!-- Syntheses (Finegan 1996) and chronosequence studies show that secondary forests mostly regenerate (~50-80%, compared to old-growth forests) rather quickly (decades, < 20 years), mainly with respect to tree height, above-ground biomass (Poorter et al 2016), and species richness, especially in wetter regions *[@rozendaal19; @onyekwelu16]*. -->

<!-- However, while restoring species richness may be enough to maintain some ecosystem functions like carbon storage (Liu et al 2018), it does not guarantee the restoration of species composition. -->

<!-- Instead, changes to species composition likely last up to centuries,  -->


<!-- [High] Regional biodiversity [can] affects/increases the uncertainty about the local occurrences and outcomes of specific species interactions, -->

<!-- such as after dispersal and/or niche overlap [CITE-niche, neutral theory]. -->

<!-- [At the same time,] Diverse local management activity modifies demographic states/profiles of various taxa's population dynamics. -->

<!-- For example, active timber plantations strongly promote the population growth of focal taxa at the expense of non-focal taxa. -->

<!-- After abandonment, however, the ecosystem likely reflects how continuous regional ecological processes look different given past management. -->

<!-- such as seed dispersal from nearby primary forest edges. -->

<!-- [These] Interactions between background ecology and human management ultimately have both local and general implications for the potential conservation/stability of ecosystem services/functions -->

<!-- like biomass/carbon storage and biodiversity maintenance, -->

<!-- as well as manager livelihood. -->

<!-- Slower changes in composition can also be influenced by seed banks, herbivore communities, and dispersal from the surrounding landscape, all of which may affect diverging restoration trajectories among tropical forests *(@nordon15, Christensen 2014, Munroe et al 2013, Chazdon et al 2007)*. -->

<!-- but lagging changes in composition may contribute to reduced effects of diversity on other forest functions (Griess et al 2012). -->

<!-- Restoring species composition more quickly is likely a place where active forest managers can have the most unique impacts. -->

<!-- For land managers / foresters with interest in conservation, inheriting land affected by past decisions is a reality. One of the legacies is where the land was placed. To best manage it in the future, an initial assessment of the ecological status of the land is important to understand it's likely trajectory, and what it will need in the future for tailed services/conservation/protection. -->

<!-- Edge effects are known for degrading primary forest, but they can also be used to assist reforestation. -->

<!-- Traditional edge effects act by mortality of large trees that makes room for pioneer species to enter, but existing interior pioneer species also have dispersal radii that overlap with the adjacent exterior, potentially facilitating regeneration. -->

<!-- Encroachment vs. facilitation relies on a balance between mortality (per area) and dispersal + establishment + stem growth. -->

<!-- So pioneer species can be helpful for reforestation though they are typically seen as bad for old forest conservation. -->



<!-- Especially for abandoned land that regenerates via various processes (Stanturf et al 2014), the proximity to less disturbed habitat can affect the composition of the regrowing community by changing effective seed dispersal kernels and probability of establishment (Wandrag et al 2017, Guariguata & Ostertag 2001), along with animal disperser communities themselves (Gilroy et al 2014). -->



<!-- Edge effects can also operate via the style of management, including logging decisions (Edwards et al 2014, Clark et al 2012) and land-use history generally (Omeja et al 2012), can also affect stand diversity maintenance, -->



<!-- possibly by changing early tree survival probabilities, growth rates, and/or competition, -->

<!-- but surprisingly less likely facilitation by nitrogen-fixing trees (Lai et al 2018). -->

<!-- It may also be that due to both high recruitment and mortality (turnover) of pioneering species' stems, transitions from early- to late-successional communities may be more complex than gradual (van Greugel et al 2007). -->



<!-- To understand the ecological principles behind secondary forest regeneration (Hulshoff & Powers 2019), here we study the regeneration of an abandoned timber plantation as a function of distance from surrounding native forest. -->

<!-- -   how can we expect it to regrow? -->
<!-- -   how far/much [effort] do we need to re-seed? -->

<!-- We hypothesized that planted canopy species would facilitate regeneration by reducing competitive suppression of more shade-tolerant taxa by pioneering species, having mixed effects on stand diversity. -->

<!-- We also considered how the legacy plantation canopy structure mediated forest stand effects via changes in abiotic conditions like light availability and microtopography (Powers & Peréz-Aviles 2012). -->

