here::i_am("figs/map.R")
site <- magick::image_read(here::here("figs/map.png")) %>% magick::image_ggplot()
Osa <- magick::image_read(here::here("figs/map_Osa.jpg")) %>% magick::image_ggplot()
pochote <- magick::image_read(here::here("figs/pochote.jpg")) %>% magick::image_ggplot()
sitePlot <- ggpubr::ggarrange(Osa, site, pochote, labels = c("a", "b", "c"))
# ggsave(filename = "figs/figmap.png", width = 3, height = 3, units = "in")
