---
title: "Osa data exploration"
output:
  html_notebook:
    toc: yes
    code_folding: hide
    theme: spacelab
    fig_caption: yes
---

```{r setup}
library(knitr); opts_chunk$set(echo=F, include=F)
library(here); source(here("analysis/stats.R")); plotVarsTbl; plotVarsTbl$varData
library(ggbeeswarm) #quasirandom()
library(ggpmisc) #stat_poly_eq()
library(ggpubr) #ggarrange()
```

# Results

## Shade, *biomass*, *richness*

```{r plots}
plotResultsTbl <- plotVarsTbl %>%
  mutate(statTest = map(.x = varData,
                        .f = ~ .x %>% lm(formula = median ~ dist)),
         normalTest = map(.x = statTest, #needstatcol1st
                         .f = ~ .x %>% residuals() %>% shapiro_test()),
         varianceTest = map(.x = varData, #OGdata
                            .f = ~ .x %>%
                              levene_test(formula = median ~ as.factor(dist))),
         statPrint = map(.x = statTest, .f = ~ .x %>% summary()), #orglast
         isNormal = map(.x = normalTest,
                        .f = ~ if_else(.x$p.value > 0.05, T, F)),
         isHomosced = map(.x = varianceTest,
                          .f = ~ if_else(.x$p > 0.05, T, F))) %>%
  unnest(cols = c(isNormal, isHomosced)) %>% #nowlogicalnotlist
  mutate(isModelOK = if_else(isNormal && isHomosced, T, F), #bug-notjoint?
         isSignif = map_if(.x = statPrint, .p = isModelOK,
                           .f = ~ if_else(.x$coefficients[[8]] < 0.11, #p
                                          true = T, false = F),
                           .else = ~ NA)) %>%
  unnest(cols = isSignif) %>%
  mutate(graph = map(.x = varData,
                     .f = ~ .x %>%
                       ggplot(aes(x = dist, y = median)) +
                       geom_quasirandom() + 
                       geom_smooth(method = "lm") +
                       stat_poly_eq(formula = y ~ x, parse = T,
                                    aes(label = stat(..p.value.label..)))))
plotResultsTbl; plotResultsTbl$graph #ggarrange(.[[1]], .[[2]]) #buggy
```

- re-model biomass, height
- spg et al. vars at tree or plot level?

## Taxa

```{r trees}
treeVarsTbl$varData
treeResultsTbl <- treeVarsTbl %>%
  mutate(statTest = map(.x = varData,
                        .f = ~ .x %>% lm(formula = median1 ~ dist)),
         normalTest = map(.x = statTest, #needstatcol1st
                         .f = ~ .x %>% residuals() %>% shapiro_test()),
         varianceTest = map(.x = varData, #OGdata
                            .f = ~ .x %>%
                              levene_test(formula = median1 ~ as.factor(dist))),
         statPrint = map(.x = statTest, .f = ~ .x %>% summary()), #orglast
         isNormal = map(.x = normalTest,
                        .f = ~ if_else(.x$p.value > 0.05, T, F)),
         isHomosced = map(.x = varianceTest,
                          .f = ~ if_else(.x$p > 0.05, T, F))) %>%
  unnest(cols = c(isNormal, isHomosced)) %>% #nowlogicalnotlist
  mutate(isModelOK = if_else((isNormal && isHomosced), T, F), #bug-notjoint?
         isSignif = map_if(.x = statPrint, .p = isModelOK,
                           .f = ~ if_else(.x$coefficients[[8]] < 0.11, #p
                                          true = T, false = F),
                           .else = ~ NA)) %>%
  unnest(cols = isSignif) %>%
  mutate(graph = map(.x = varData,
                     .f = ~ .x %>%
                       ggplot(aes(x = dist, y = median1)) +
                       geom_quasirandom() + 
                       geom_smooth(method = "lm") +
                       stat_poly_eq(formula = y ~ x, parse = T,
                                    aes(label = stat(..p.value.label..)))))
treeResultsTbl; treeResultsTbl$graph #ggarrange(.[[1]], .[[2]]) #buggy
```
